### ISSUE TITLE
Feature Request: apply this project to Xrebel

### ISSUE THREAD

**Issue by meiMingle** [sql-formatter-org/sql-formatter#222]
**Describe the Feature**
It is recommended to apply this project to Xrebel, currently Xrebel cannot format the following sql correctly, it displays the user variables `@rownum` as `undefined`.And I test it with the demo of this project,it works well.
```mysql
select  @rownum := @rownum + 1 AS id,supplier_name,city from
(select * from suppliers join addresses on suppliers.address_id=addresses.id)
as suppliers,(SELECT @rownum := 0 ) r
where supplier_id>500
order by supplier_name asc,city desc;
```

**Why do you want this feature?**
The sql format of Xrebel is terrible

**Info**

- How would you be calling / using the script?
Work with Xrebel.
- What SQL language(s) does this apply to?
  mysql/mariadb
- What Node version? (If applicable)

**Additional context**
Other places mentioning similar issues：
https://youtrack.jetbrains.com/issue/DBE-15142/Xrebel-display-all-User-Defined-Variables-in-sql-as-undefined
https://plugins.jetbrains.com/plugin/4441-jrebel-and-xrebel/reviews#review=63918

**Comment by nene** [comment]
If I understand correctly, you have a problem with XRebel, which uses this library under the hood to format SQL (or at least I know it did so in the past).

You are probably hoping to reach XRebel developers through this issue tracker, as this repo is under the zeroturnaround organization. In a sense you have reached one... I used to work on XRebel in ZeroTurnaround, but not any more, now I'm just maintaining this library from my own free time. There's been zero interest from ZeroTurnaround in this library since. My best guess is that they're still using a several-years old version of this library. Well... frankly I wasn't even sure whether XRebel is even around any more (several projects got closed down when the company got sold), but glad to hear it's still functioning.

I think you're best off contacting their customer support. Maybe you'll have more success if you tell them something concrete like, hey, I think you're using an outdated version of this library, would you mind upgrading it?

**Comment by meiMingle** [comment]
> If I understand correctly, you have a problem with XRebel, which uses this library under the hood to format SQL (or at least I know it did so in the past).
> 
> You are probably hoping to reach XRebel developers through this issue tracker, as this repo is under the zeroturnaround organization. In a sense you have reached one... I used to work on XRebel in ZeroTurnaround, but not any more, now I'm just maintaining this library from my own free time. There's been zero interest from ZeroTurnaround in this library since. My best guess is that they're still using a several-years old version of this library. Well... frankly I wasn't even sure whether XRebel is even around any more (several projects got closed down when the company got sold), but glad to hear it's still functioning.
> 
> I think you're best off contacting their customer support. Maybe you'll have more success if you tell them something concrete like, hey, I think you're using an outdated version of this library, would you mind upgrading it?

Thanks Reply. Since I see that the main body of this repository is zeroturnaround, I guess it might be a library of the organization that Xrebel belongs to. As you said, I just wanted to reach XRebel developers through this issue tracker. In fact, the similar issues mentioned in the Additional context are all raised by me. I first raised this issue with Xrebel at support@xrebel.com and provided the logs (redacted according to company requirements), but they suspected I was deliberately hiding the registration information and didn't follow up on the issue. I am pessimistic that this problem may never be fixed again. Xrebel may also be one of the closed projects, because its latest version was released in September 2021, more than half a year ago, while Jrebel frequently renew. It would be a shame if that was the case, xrebel is an amazing tool.

**Comment by nene** [comment]
Completed a transfer of this repo away from ZeroTurnaround organization, so there should be less confusion over the ownership in the future.

Sad that they are letting the software rot and aren't bothering to upgrade their dependencies. Unfortunately there's not much I can do.
