### ISSUE TITLE
tabulateAlias true doesn't work after comment in SELECT

### ISSUE THREAD

**Issue by Dunky13** [sql-formatter-org/sql-formatter#236]
**Input data**
VSCode: `Prettier-SQL.tabulateAlias: true`

**Expected Output**

```sql
SELECT
  a       AS alpha,
  beta    AS superBeta,
  -- c AS charlie
  d AS delta
FROM
   alphabet
```

**Actual Output**

```sql
SELECT
  a       AS alpha,
  beta    AS superBeta,
  -- c AS charlie
  d       AS delta
FROM
   alphabet
```

It does not tabulate after a comment line

**Comment by nene** [comment]
Thanks for the report.

This feature really needs a complete rewrite. This bug is actually even worse as the implementation doesn't really distinguish comments from actual code and ends up formatting the comments too. The same problem happens with the `commaPosition: tabular` option. For example the following:

```sql
SELECT
  a AS alpha,
  biglongname AS superBeta,
  -- c AS charlie,
  d AS delta,
  g AS gamma
FROM
   alphabet
```

Gets formatted as:

```sql
SELECT
  a           AS alpha    ,
  biglongname AS superBeta,
  -- c        AS charlie  ,
  d           AS delta    ,
  g           AS gamma
FROM
  alphabet
```

Note the formatting happening inside a comment. Really bad :(

**Comment by Dunky13** [comment]
That I wouldn't mind as much, but would like for it to be fully formatted.
Not end on the first comment

**Comment by nene** [comment]
There could be a band-aid fix to ignore the comments, but really the current implementation is super-fragile and should be completely replaced.

**Comment by Dunky13** [comment]
Idea for rewrite: split the query into an object. With select, from, join etc being keys (Possibly nested). And then format each accordingly?

**Comment by Songothao** [comment]
how to do

**Comment by nene** [comment]
Closing this as the `tabulateAlias` option will be removed in the upcoming 14.0.0 release.
