### ISSUE TITLE
Feature Request: Support an option to insert explicit AS in front of aliases

### ISSUE THREAD

**Issue by antimirov** [sql-formatter-org/sql-formatter#533]
**Describe the Feature**
It would be nice if there was an option to insert AS in front of aliases explicitly:

```sql
-- before
SELECT p.*, c.name FROM product p
LEFT JOIN company c ON c.id = p.company_id

-- after
SELECT p.*, c.name FROM product AS p
LEFT JOIN company AS c ON c.id = p.company_id
```

**Why do you want this feature?**
Sometimes we forget to add `AS` before aliases, and it makes it harder to spot them later among hundreds of lines of code, like in this example it's difficult to spot `p` or `c`. I'm giving these one-character examples to amplify my point, of course.

**Comment by nene** [comment]
Well, we used to have such a feature, but we dropped it because the implementation was buggy.

For now this is unlikely to come back. To properly implementing it, we need to first correctly parse the SQL to a syntax tree, which the formatter currently doesn't do. I'm working on [an SQL parser library][sql-parser-cst] that could make this possible.

Well, it's already possible to implement this sort of explicit alias transform by using that library:

```ts
import { parse, show, cstVisitor } from "sql-parser-cst";

const makeAliasesExplicit = cstVisitor({
  alias: (node) => {
    if (!node.asKw) {
      node.asKw = {
        type: "keyword",
        name: "AS",
        text: "AS",
        trailing: [{ type: "space", text: " " }],
      };
    }
  },
});

const cst = parse("SELECT t.firstname fname, t.lastname lname FROM my_table t", {
  preserveComments: true, preserveNewlines: true, preserveSpaces: true,
});
makeAliasesExplicit(cst);

// prints: SELECT t.firstname AS fname, t.lastname AS lname FROM my_table AS t
console.log(show(cst));
```

Though for now the parser only works with SQLite (with partial support for BigQuery and MySQL).

[sql-parser-cst]: https://github.com/nene/sql-parser-cst/

**Comment by nene** [comment]
I'm closing this issue, as it's not going to be implemented in sql-formatter. Perhaps in some future re-incarnation of sql-formatter.
