### ISSUE TITLE
[FORMATTING] Params not working when dialect is postgresql.

### ISSUE THREAD

**Issue by wirekang** [sql-formatter-org/sql-formatter#546]
**Input data**

```sql
select $1
```
with params:
```ts
["a"]
```

**Expected Output**

```sql
select a
```

**Actual Output**

```sql
select
```

**Usage**

- How are you calling / using the library?

```ts
console.log(
  formatDialect("select $1", {
    dialect: postgresql,
    params: ["a"],
  })
);
```
- What SQL language(s) does this apply to?
  Postgres
- Which SQL Formatter version are you using?
  12.0.4

**Comment by wirekang** [comment]
Parameter placeholders seem to count from zero. 
# Case 1
## Input

```sql
select $0
```

```ts
["a"]
```

## Output
```sql
select a
```

# Case 2
## Input

```sql
select $1
```

```ts
["a","b"]
```

## Output
```sql
select b
```

**Comment by nene** [comment]
For the numbered placeholders one should really use an object like `{1: "a", 2: "b"}` instead of an array. [It's pretty clearly documented.](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/params.md#numbered-placeholders)

I agree it's not the most intuitive approach, but then again, making `$1` correspond to index `0` is similarly not quite intuitive. For now the API is like so by design.

**Comment by wirekang** [comment]
Thank you for your kind answer.
