### ISSUE TITLE
Feature Request: Separate Trino and Presto SQL dialect

### ISSUE THREAD

**Issue by mosabua** [sql-formatter-org/sql-formatter#620]
**Describe the Feature**

Currently the SQL dialect list at https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/language.md seems to indicated that Trino and Presto use the same SQL dialect. This should be separated

**Why do you want this feature?**

Trino supports many more functions and also different SQL statements like MATCH_RECOGNIZE, MERGE and many others that are not supported by Presto. In order to avoid user confusion is might be better two maintain two dialect definitions.  Also note that the two projects are maintained and developed separately so the diff will grow even more over time.

**Comment by mosabua** [comment]
cc @verhovsky

**Comment by mosabua** [comment]
Related to https://github.com/sql-formatter-org/sql-formatter/pull/297

**Comment by verhovsky** [comment]
It would of course be great to have a dedicated grammar but I am not going to work on this so unless someone else wants to, the only thing that can realistically happen here is removing "/ Presto" from the README. That line is just there for search engines and people ctrl-f'ing. I thought that not having it would be a net negative because they're not that different in my opinion, and unless there's some other presto JavaScript formatter that I am unaware of, it's more useful to use a Trino formatter for presto than not using anything or using a generic sql formatter. If Trino is mostly a superset then you wouldn't be using the extra keywords that this grammar is splitting lines on anyway.

@nene for context, Presto started at facebook, they open sourced it then the authors (that used to work at Facebook) and Facebook had some disagreement so the authors forked presto and called it trino. So now there's two similar things with different names, resulting in everyone wasting a bit of  time, like we're doing on this issue.

https://en.wikipedia.org/wiki/Presto_(SQL_query_engine)

https://en.wikipedia.org/wiki/Trino_(SQL_query_engine)

**Comment by mosabua** [comment]
Fair enough. I am fine with this as long as the SQL Formatter team understands that the two dialects are not the same and any user experience for Presto users might be a bit wonky. I guess we can just leave it as is until we get complaints.

**Comment by nene** [comment]
I think as long as putting these two to the same bucket doesn't produce any actual problems, no real need to separate them.

Could just clarify the docs though to make it more explicit that we specifically support Trino, but that should also work for Presto.

**Comment by nene** [comment]
Improved docs.
