### ISSUE TITLE
[FORMATTING] `bigquery` date is upper cased when used as an identifier

### ISSUE THREAD

**Issue by Anthony-Fiddes** [sql-formatter-org/sql-formatter#647]
This seems like it may be similar to issue #629. It looks like date is not a reserved keyword as shown [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#reserved_keywords).
 
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT
  date
FROM
  test
```

**Expected Output**

```sql
SELECT
  date
FROM
  test
```

**Actual Output**

```sql
SELECT
  DATE
FROM
  test
```

**Usage**

- How are you calling / using the library?
  - I'm using the CLI, with keywordCase set to upper and the language set to bigquery
- What SQL language(s) does this apply to?
  - BigQuery
- Which SQL Formatter version are you using?
  - 13.0.0

**Comment by nene** [comment]
Thanks for reporting.

Because of how sql-formatter works, there's currently no really good solution for this.

1. On one hand we could limit the uppercasing to just the actual reserved keywords in BigQuery, but that will leave us with lots of cases where one would expect the word to be capitalized.
2. On another hand we could extend it to capitalize all keywords (including non-reserved ones), which will result in lots of cases of extra capitalization, like seen here.

In general I've tried to steer more towards the first solution, but not 100% so. Notably I've included data type keywords to the list of things to be capitalized, which mostly isn't a problem, as one is unlikely to have a column named `int64`, but there are a few column names which do come up more often and conflict with data type names like `date`, `time`, `timezone`. But I think it's still more likely that one uses `DATE` as a data type rather than as a column name.

Perhaps you're instead interested in trying out [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst), which is another SQL formatting tool that I've written, that solves context-sensitive problems like this. It also happens to have BigQuery as one of the few dialects that it supports.

**Comment by Anthony-Fiddes** [comment]
Thanks for taking the time to explain that all to me! I actually did check out your prettier plugin and it does everything I want it to, but I couldn't figure out how to run it globally (like outside of a node project).

Do you have any tips there? I would love to migrate!

**Comment by Anthony-Fiddes** [comment]
What I tried:

I installed the plugin globally, then set up this config

```
// ~/.prettierrc.js
module.exports = {
	plugins: ["prettier-plugin-sql-cst"],
	// Other Prettier options...
	overrides: [
		{
			files: ["*.sql"],
			options: { parser: "bigquery" },
		},
	],
};
```

And then I tried running it:

```
prettier --write test.sql
[error] Cannot find package 'prettier-plugin-sql-cst' imported from /home/{me}/code/noop.js
```

**Comment by Anthony-Fiddes** [comment]
Also tried with an absolute path to my install of the plugin

```
❯ prettier --write test.sql
[error] Directory import '/usr/lib/node_modules/prettier-plugin-sql-cst' is not supported resolving ES modules imported from /usr/lib/node_modules/prettier/index.mjs
[error] Did you mean to import /usr/lib/node_modules/prettier-plugin-sql-cst/dist/index.js?

~/code ··································································································································· 10:49:17
❯ nvim # me making the change suggested above

~/code ································································································································ 9s 10:49:35
❯ prettier --write test.sql
test.sql
[error] test.sql: InvalidDocError: Unexpected doc.type 'concat'.
[error] Expected it to be 'cursor', 'indent', 'align', 'trim', 'group', 'fill', 'if-break', 'indent-if-break', 'line-suffix', 'line-suffix-boundary', 'line', 'label', or 'break-parent'.
[error]     at traverseDoc (file:///usr/lib/node_modules/prettier/index.mjs:14762:13)
[error]     at propagateBreaks (file:///usr/lib/node_modules/prettier/index.mjs:15094:3)
[error]     at printDocToString (file:///usr/lib/node_modules/prettier/index.mjs:15499:3)
[error]     at coreFormat (file:///usr/lib/node_modules/prettier/index.mjs:18065:18)
[error]     at async formatWithCursor (file:///usr/lib/node_modules/prettier/index.mjs:18259:14)
[error]     at async formatFiles (file:///usr/lib/node_modules/prettier/internal/cli.mjs:6800:18)
[error]     at async main (file:///usr/lib/node_modules/prettier/internal/cli.mjs:6992:5)
[error]     at async Module.run (file:///usr/lib/node_modules/prettier/internal/cli.mjs:6946:5)
```

**Comment by nene** [comment]
The error message looks like there's something going wrong within Prettier itself. I suspect you're using Prettier 3.x, which the plugin doesn't support yet. Try if it works with Prettier 2.x.

**Comment by Anthony-Fiddes** [comment]
That worked, thanks! That would've taken me ages to figure out. It may be helpful to add the supported versions of prettier to the plugin's README.

**Comment by nene** [comment]
Glad it worked. Added a small remark about Prettier versions to the README.
