### ISSUE TITLE
[FORMATTING] Parse error. Unexpected "@variable" at line X column Y

### ISSUE THREAD

**Issue by DanielJerrehian** [sql-formatter-org/sql-formatter#656]
**Input data**

Which SQL and options did you provide as input?

```sql
CREATE PROCEDURE schema.procedure 
@variable BIGINT,
AS
BEGIN
SET NOCOUNT ON
UPDATE schema.table
SET 
username = UPPER(username), 
id = @variable 
END
```

**Expected Output**

Expected output similar to the following (not expecting it to be identical):
```sql
CREATE PROCEDURE schema.procedure

AS BEGIN
SET
    NOCOUNT ON
    UPDATE schema.table
SET
    username = UPPER(username),
    id = @variable 
END
```

**Actual Output**

Unable to format SQL: Error: Parse error. Unexpected "@variable" at line X column Y

**Usage**

- How are you calling / using the library?
Via VSCode extension "Prettier SQL VSCode"

- What SQL language(s) does this apply to?
T-SQL

- Which SQL Formatter version are you using?
v1.6.0

**Comment by nene** [comment]
Hi Daniel, thanks for reporting. However, I see no actual bugs in here...

1. [Please read the FAQ](https://github.com/sql-formatter-org/sql-formatter#parse-error-unexpected--at-line-) to see how to set the dialect to Transact-SQL
2. Don't use the "Prettier SQL VSCode" extension. It's no more maintained and there's nothing I can do about it. Use the official [SQL Formatter VSCode](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc) extension instead.
3. [As mentioned in the README](https://github.com/sql-formatter-org/sql-formatter#sql-formatter---), formatting of stored procedures is not supported. The best SQL Formatter tries to do is not to crash when seeing stored procedure syntax. But the result of formatting it will likely be pretty ugly.
4. The formatter does crash when it encounters `schema.procedure` because `SCHEMA` is a [reserved word in Transact-SQL](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15). So I think that's not a bug. I suppose you are actually not naming your schema as `schema`.

**Comment by DanielJerrehian** [comment]
Thanks for the reply, I appreciate the suggestions. And yes, the `schema` is not actually named `schema` :)
