### ISSUE TITLE
Cannot read properties of undefined (reading 'nestedBlockComments')

### ISSUE THREAD

**Issue by MrSwitch** [sql-formatter-org/sql-formatter#715]
**Describe the bug**

Given any SQL in JS, i.e. ...
```js
const query = SQL`
	SELECT 1
`;
```

And using a `.prettierrc.js` like...

```js
module.exports = {
	embeddedSqlTags: ['SQL'],
	embeddedSqlParser: 'mysql',
	dialect: 'mysql',
	indentStyle: 'tabularLeft',
	plugins: [
		'prettier-plugin-embed',
		'prettier-plugin-sql',
	],
};
```

**Expected behavior**
Expect no bug

**Actual behavior**
But whilst it does format it the item, we also get the error...

> TypeError: Cannot read properties of undefined (reading 'nestedBlockComments')
    at Tokenizer.buildRulesBeforeParams (file:node_modules/sql-formatter/dist/index.js:14969:20)
    at new Tokenizer (file:node_modules/sql-formatter/dist/index.js:14946:35)
    at dialectFromOptions (file:node_modules/sql-formatter/dist/index.js:15192:14)
    at createDialect (file:node_modules/sql-formatter/dist/index.js:15186:15)
    at formatDialect (file:node_modules/sql-formatter/dist/index.js:16614:24)
    at Object.print (file:node_modules/prettier-plugin-sql/lib/index.js:47:31)
    at callPluginPrintFunction (file:node_modules/prettier/index.mjs:22296:20)
    at printAstToDoc (file:node_modules/prettier/index.mjs:22251:22)
    at async textToDoc (file:node_modules/prettier/index.mjs:22218:16)
    at async Ur (file:node_modules/prettier-plugin-embed/dist/index.js:1437:15)

**Usage**

- How are you calling / using the library? 
   - Using `prettier-plugin-sql` and `prettier-plugin-embed` they will pick up SQL in JS such as...
- What SQL language(s) does this apply to?
   - MySQL afaik
- Which SQL Formatter version are you using?
   - 15.2.0

ps: Many thanks for this project it's awesome!

**Comment by Sec-ant** [comment]
I think you're using the option in a wrong way.

The [`dialect`](https://github.com/un-ts/prettier/tree/master/packages/sql#parser-options:~:text=//%20default%20%60sql%60-,dialect,-%3A%20string%20//%20%60JSOX) in the `prettier-plugin-sql` plugin is expecting a **stringified** **JSON-like** (will be parserd by `JSOX`) [object](https://github.com/sql-formatter-org/sql-formatter/blob/3483499b9c607ca7caf204a1899f487d6fe43d74/src/dialect.ts#L8-L12), but you're setting it to a string `'mysql'`. That's why the [tokenizer](https://github.com/sql-formatter-org/sql-formatter/blob/3483499b9c607ca7caf204a1899f487d6fe43d74/src/dialect.ts#L36) throws this error.

You can discard the `dialect` option and simply use the [`language`](https://github.com/un-ts/prettier/tree/master/packages/sql#parser-options:~:text=//%20sql%2Dformatter-,language,-%3A%0A%20%20%20%20%7C%20%27sql) option to tell the plugin you're formatting mysql language.

Also, you don't need the `embeddedSqlParser` option if you're using the `prettier-plugin-sql` plugin to format your embedded sql code. [`embeddedSqlParser`](https://github.com/Sec-ant/prettier-plugin-embed?tab=readme-ov-file#embeddedsqlparser) is only for the `prettier-plugin-sql-cst` plugin.

**Comment by nene** [comment]
Yep. As @Sec-ant said. Just use the `language` option. The main purpose of the `dialect` option is defining a custom SQL dialect.

Also be aware that [indentStyle: tabularLeft](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/indentStyle.md) is deprecated and will be removed in future versions of the formatter.

**Comment by MrSwitch** [comment]
Thankyou both @Sec-ant and @nene for pointing helping me out there.
