### ISSUE TITLE
Supplying empty regex crashes browser

### ISSUE THREAD

**Issue by JulianVGit** [sql-formatter-org/sql-formatter#754]
When supplying and empty regex as a custom param for syntax, the browser crashes:

```js
format('SELECT * FROM whatever', {
  language: 'sql',
  paramTypes: {
      custom: [{regex: ''}]
  },
}
```

**Comment by nene** [comment]
More correctly, the code will enter an infinite loop, because you have defined a parameter to be an empty string, and there can are infinitely many empty strings in any string.

The formatter could possibly check whether the supplied regex is an empty string, and throw a more friendly error message instead of getting stuck in infinite loop. If you're really interested in getting a better error in this specific case, I'm open to a pull request.

However there are infinitely many regexes that would end up matching empty string (for example `(|)`) and therefore triggering an infinite loop. It's not really feasible to properly validate them all.

**Comment by nene** [comment]
Oh well. As I'm already looking into this code, might as well add this little extra check.
