### ISSUE TITLE
[FORMATTING] sqlite UPSERT formatting

### ISSUE THREAD

**Issue by ulikunitz** [sql-formatter-org/sql-formatter#783]
**Input data**

Which SQL and options did you provide as input?

I use Prettier SQL VSCode with sqlite mode.

```sql
insert into  test_table(id, name)
values (1, 'foobar') 
on conflict (id) do update
set name = 'foobar';
```

**Expected Output**

```sql
insert into
        test_table (id, name)
values
        (1, 'foobar')
on conflict (id) do update
set
        name = 'foobar';
```

**Actual Output**

```sql
insert into
        test_table (id, name)
values
        (1, 'foobar') on conflict (id) do
update
set
        name = 'foobar';
```

I suggest to move `on conflict (id) do` to the next line.

**Usage**

- How are you calling / using the library?

I'm using the library with Prettier SQL VS Code and use sqlite mode.

- What SQL language(s) does this apply to?

Sqlite. Note that sqlite supports multiple on conflict clauses. The syntax is defined here: (https://www.sqlite.org/lang_upsert.html)  The page reports that it used the syntax from postfgresql and changed it.

- Which SQL Formatter version are you using?

Prettier SQL VSCode 1.6

**Comment by nene** [comment]
First, please read the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#im-having-a-problem-with-prettier-sql-vscode-extension). There's nothing I can do about the Prettier SQL VSCode extension.

However, this bug does exist in the latest SQL Formatter library. There are essentially two issues:

- The `ON CONFLICT` clause is not printed to a separate line
- The `UPDATE` in `DO UPDATE` is recognized as start of an `UPDATE` statement.

These can both be fixed in SQL Formatter. Though I suggest you give a try to [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst), which has full support for SQLite, and in general does much better job at formatting SQL.
