### ISSUE TITLE
[FORMATTING] Formatter adding space for sqlc macros 

### ISSUE THREAD

**Issue by B4Dmonkey** [sql-formatter-org/sql-formatter#786]
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT
  sqlc.embed(transactions),
  sqlc.embed(documents_meta)
FROM
  transactions
  JOIN documents_meta ON transactions.document_id=documents_meta.id
WHERE
  transactions.posting_date>=@start_date
  AND transactions.posting_date<=@end_date
  AND documents_meta.publishing_date=(
    SELECT
      MAX(publishing_date)
    FROM
      documents_meta
  )
ORDER BY
  transactions.posting_date DESC;
```

**Expected Output**

```sql
SELECT
  sqlc.embed(transactions),
  sqlc.embed(documents_meta)
FROM
  transactions
  JOIN documents_meta ON transactions.document_id=documents_meta.id
WHERE
  transactions.posting_date>=@start_date
  AND transactions.posting_date<=@end_date
  AND documents_meta.publishing_date=(
    SELECT
      MAX(publishing_date)
    FROM
      documents_meta
  )
ORDER BY
  transactions.posting_date DESC;
```

**Actual Output**

```sql
SELECT
  sqlc.embed (transactions),
  sqlc.embed (documents_meta)
FROM
  transactions
  JOIN documents_meta ON transactions.document_id=documents_meta.id
WHERE
  transactions.posting_date>=@start_date
  AND transactions.posting_date<=@end_date
  AND documents_meta.publishing_date=(
    SELECT
      MAX(publishing_date)
    FROM
      documents_meta
  )
ORDER BY
  transactions.posting_date DESC;
```

**Usage**

- How are you calling / using the library?
I'm calling this using the prettier vs code pluqin
- What SQL language(s) does this apply to?
This is for sqlite when paired with sqlc
- Which SQL Formatter version are you using?
v11.0.0

**Additional information**
When I'm running the formatter it's inserting a space for sqlc.embed(transactions). This is an issue because it breaks sqlc's compilation. As best I can tell theres no configuration to prevent inserting this space.

**Comment by nene** [comment]
Thanks for reporting, but I should point out that you're using a pretty outdated version of SQL Formatter library (the latest version is 15.x). Perhaps also read the [FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#im-having-a-problem-with-prettier-sql-vscode-extension).

However this problem is also present in the latest version. There's an old issue open for this #444. So I'm closing this as duplicate.

I might suggest you instead give a try to [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst) which does not have this issue and has in general pretty solid SQLite support.
