### ISSUE TITLE
[FORMATTING] `REPLACE` Not Properly Uppercased in PostgreSQL Dialect

### ISSUE THREAD

**Issue by etzelc** [sql-formatter-org/sql-formatter#813]
When using the PostgreSQL dialect with the following configuration:
```
{
  "language": "postgresql",
  "dialect": "postgresql",
  "tabWidth": 2,
  "keywordCase": "upper",
  "dataTypeCase": "lower",
  "functionCase": "lower",
  "identifierCase": "lower",
  "expressionWidth": 80,
  "linesBetweenQueries": 1
}
```
The formatter incorrectly converts `REPLACE` to lowercase (`replace`) even though keywordCase is set to "upper". 

This happens since the upgrade from 15.4.7 to 15.4.8.

**Input data**

```sql
CREATE
OR REPLACE function empty_function () returns void AS $$
BEGIN
  -- Do nothing
END;
$$ language plpgsql;
```

**Expected Output**

```sql
CREATE
OR REPLACE function empty_function () returns void AS $$
BEGIN
  -- Do nothing
END;
$$ language plpgsql;

```

**Actual Output**

```sql
CREATE
OR replace function empty_function () returns void AS $$
BEGIN
  -- Do nothing
END;
$$ language plpgsql;
```

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add 'REPLACE' to the list of keywords in the postgresql.keywords.ts file to ensure it's treated as a keyword and formatted correctly.

You can review changes in this commit: https://github.com/wwqwq2313/sql-formatter-org-sql-formatter-813/commit/1aa61400fbe8173b6e224b00e4fdf70b7d2b7265.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by nene** [comment]
Thanks for reporting.

The issue is that the formatter doesn't recognize `OR REPLACE` as part of `CREATE FUNCTION`.

Also I should point out the following:

- Using `"dialect": "postgresql"` has no effect when `language` option is also present. If anything it might lead to a crash in the future, as strings are not valid values for the `dialect` option. Really, the `dialect` option does the same as the `language` option. But it makes no sense to use it in config file - only when calling the library through code.
- The `identifierCase` option is experimental and will result in lots of keywords being converted to lowercase. Really the only time to use it would be when you either want all of the code to be in either lower- or uppercase. Or at least, I wouldn't use it. Though if you're happy with the result, feel free to use it.

**Comment by etzelc** [comment]
Thank you for your feedback on the config file. I’ll test your suggestions.

And a big thanks for resolving the issue so quickly! 👍
